
# 베이스 이미지 지정
FROM node:20

# 컨테이너 내에서 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json 및 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 앱 소스 복사
COPY . .

# 앱이 3000 포트에서 바인딩되므로, EXPOSE 를 사용하여 docker 실행시 컨테이너에 매핑되도록 함
EXPOSE 3000

# 앱 실행 명령어 정의
CMD [ "node", "app.js" ]